---
title: "Elevated death rate due to infection"
author: "ekamau"
date: "2024-03-24"
output: html_document
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, eval=TRUE, results='hide'}

# load libraries:
if (!require("pacman")) install.packages("pacman")
p_load(tidyverse, reshape2, patchwork, scales)

```

$~$

```{r echo=TRUE, eval=TRUE}

# functions for the system equation solutions:
constant_foi <- function(a, lambda, mu){
  prop_x = 1-((lambda-mu)/(lambda*exp((lambda-mu)*age)-mu)) # seropositive proportion v1 == includes death
  prop_x2 = 1-exp(-lambda*a) # seropositive proportion v2 == constant FOI
  
  return(c(prop_x, prop_x2))
}

ages <- seq(0.1,65,by=0.1)

```

$~$
Scenario where there's low risk of death due to infection (mu == $\mu$) and the force of infection ($\lambda$) is assumed to be constant:
$~$

```{r echo=TRUE, eval=TRUE}

mu <- 0.04; lambda = 0.1
prop_seropos_df <- data.frame()
for(age in ages){
  out = constant_foi(age, lambda, mu)
  prop_seropos_df = rbind(prop_seropos_df, c(age, out))
}

colnames(prop_seropos_df) <- c("age", "prop_death", "prop_nodeath")
prop_seropos_df1 <- reshape2::melt(prop_seropos_df, id = c("age"), variable.name = "Proportion")

figA <- prop_seropos_df1 %>% 
  ggplot(aes(x = age, y = value, color = as.factor(Proportion))) +
  geom_line() +
  scale_color_manual(values = c("prop_nodeath"="#0000FF", "prop_death"="#E69F00")) +
  labs(x = "Age, years", y = "Seropositivity", title = "A. Low mu") +
  guides(color = "none") +
  scale_x_continuous(trans="log10", breaks = c(0.1,1,5,10,15,20,seq(30,70,by=15)),
                labels = function(x){sprintf("%.0f", x)}) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 6)) 


```

$~$
Scenario where there's high risk of death due to infection (mu == $\mu$) and the force of infection ($\lambda$) is assumed to be constant:
$~$

```{r echo=TRUE, eval=TRUE}

mu <- 1.2; lambda = 0.15
prop_seropos_df2 <- data.frame()
for(age in ages){
  out = constant_foi(age, lambda, mu)
  prop_seropos_df2 = rbind(prop_seropos_df2, c(age, out))
}

colnames(prop_seropos_df2) <- c("age", "prop_death", "prop_nodeath")
prop_seropos_df3 <- reshape2::melt(prop_seropos_df2, id = c("age"), variable.name = "Proportion")

figB <- prop_seropos_df3 %>% 
  ggplot(aes(x = age, y = value, color = as.factor(Proportion))) +
  geom_line() +
  scale_color_manual(name = "",
                     values = c("prop_nodeath"="#0000FF", "prop_death"="#E69F00"),
                     labels = c("w/ death", "w/o death")) +
  labs(x = "Age, years", y = "", title = "B. High mu") +
  scale_x_continuous(trans="log10", breaks = c(0.1,1,5,10,15,20,seq(30,70,by=15)),
                labels = function(x){sprintf("%.0f", x)}) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 6))


```

```{r echo=TRUE, eval=TRUE, out.width = "100%"}

figA + figB + plot_layout(guides = "collect") & theme(legend.position = 'bottom')

```